version: "3.3"

services:
  backend:
    build:
      context: backend
      dockerfile: Dockerfile
    ports:
      - "8081:8081"
    depends_on:
      keycloak:
        condition: service_healthy
    environment:
      KEYCLOAK_URL: "http://keycloak:8080"
      REALM: "master"
      CLIENT_ID: "polyclient"
      CLIENT_SECRET: "jtfzpXIbb0YVGZqeJQb290zxTQ1QdxWt"

  keycloak:
    image: quay.io/keycloak/keycloak:20.0.1
    restart: always
    command: start-dev
    ports:
      - "8090:8080"
    environment:
      KEYCLOAK_ADMIN: admin
      KEYCLOAK_ADMIN_PASSWORD: admin
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:8080/realms/master"]
      interval: 10s
      timeout: 5s
      retries: 10
    volumes:
      - data:/opt/keycloak/data/

volumes:
  data: